Controllers/PaymentPaybyrdController.cs
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Core.Infrastructure;
using Nop.Plugin.Payments.Paybyrd.Localization;
using Nop.Plugin.Payments.Paybyrd.Models;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.Paybyrd.Controllers;

[AuthorizeAdmin]
[Area(AreaNames.ADMIN)]
public class PaymentPaybyrdController : BasePaymentController
{
    #region Fields

    protected readonly ILanguageService _languageService;
    protected readonly ILocalizationService _localizationService;
    protected readonly INotificationService _notificationService;
    protected readonly IPermissionService _permissionService;
    protected readonly ISettingService _settingService;
    protected readonly IStoreContext _storeContext;
    protected readonly IWebHelper _webHelper;
    protected readonly IOrderService _orderService;
    protected readonly IWorkContext _workContext;

    #endregion

    #region Ctor

    public PaymentPaybyrdController(ILanguageService languageService,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IPermissionService permissionService,
        ISettingService settingService,
        IStoreContext storeContext,
        IWebHelper webHelper,
        IOrderService orderService,
        IWorkContext workContext)
    {
        _languageService = languageService;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _permissionService = permissionService;
        _settingService = settingService;
        _storeContext = storeContext;
        _webHelper = webHelper;
        _orderService = orderService;
        _workContext = workContext;
    }

    #endregion

    #region Methods

    public async Task<IActionResult> Configure()
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
            return AccessDeniedView();

        // Load settings for a chosen store scope
        var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
        var paybyrdPaymentSettings = await _settingService.LoadSettingAsync<PaybyrdPaymentSettings>(storeScope);

        var model = new ConfigurationModel
        {
            PostPaymentOrderStatusId = Convert.ToInt32(paybyrdPaymentSettings.PostPaymentOrderStatus),
            PostPaymentOrderStatusValues = await paybyrdPaymentSettings.PostPaymentOrderStatus.ToSelectListAsync(),
            LiveApiKey = paybyrdPaymentSettings.LiveApiKey,
            TestApiKey = paybyrdPaymentSettings.TestApiKey,
            EnableTestMode = paybyrdPaymentSettings.EnableTestMode,
            WebhookId = paybyrdPaymentSettings.WebhookId,
            HFBackgroundColor = paybyrdPaymentSettings.HFBackgroundColor,
            HFPaymentBackgroundColor = paybyrdPaymentSettings.HFPaymentBackgroundColor,
            HFPrimaryColor = paybyrdPaymentSettings.HFPrimaryColor,
            ActiveStoreScopeConfiguration = storeScope
        };

        model.LiveApiKey = paybyrdPaymentSettings.LiveApiKey;
        model.PostPaymentOrderStatusId = Convert.ToInt32(paybyrdPaymentSettings.PostPaymentOrderStatus);
        model.TestApiKey = paybyrdPaymentSettings.TestApiKey;
        model.EnableTestMode = paybyrdPaymentSettings.EnableTestMode;
        model.WebhookId = paybyrdPaymentSettings.WebhookId;
        model.HFBackgroundColor = paybyrdPaymentSettings.HFBackgroundColor;
        model.HFPaymentBackgroundColor = paybyrdPaymentSettings.HFPaymentBackgroundColor;
        model.HFPrimaryColor = paybyrdPaymentSettings.HFPrimaryColor;
        model.HFTextColor = paybyrdPaymentSettings.HFTextColor;
        model.ActiveStoreScopeConfiguration = storeScope;

        if (storeScope > 0)
        {
            model.LiveApiKey_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.LiveApiKey, storeScope);
            model.PostPaymentOrderStatusId_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.PostPaymentOrderStatus, storeScope);
            model.TestApiKey_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.TestApiKey, storeScope);
            model.EnableTestMode_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.EnableTestMode, storeScope);
            model.WebhookId_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.WebhookId, storeScope);
            model.HFBackgroundColor_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.HFBackgroundColor, storeScope);
            model.HFPaymentBackgroundColor_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.HFPaymentBackgroundColor, storeScope);
            model.HFPrimaryColor_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.HFPrimaryColor, storeScope);
            model.HFTextColor_OverrideForStore = await _settingService.SettingExistsAsync(paybyrdPaymentSettings, x => x.HFTextColor, storeScope);
        }

        return View("~/Plugins/Payments.Paybyrd/Views/Configure.cshtml", model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Configure(ConfigurationModel model)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
            return AccessDeniedView();

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
        var paybyrdPaymentSettings = await _settingService.LoadSettingAsync<PaybyrdPaymentSettings>(storeScope);
        var webhookId = await FetchWebhookIdAsync(model.LiveApiKey, paybyrdPaymentSettings.WebhookId);

        // Save admin configurations
        paybyrdPaymentSettings.LiveApiKey = model.LiveApiKey;
        paybyrdPaymentSettings.TestApiKey = model.TestApiKey;
        paybyrdPaymentSettings.EnableTestMode = model.EnableTestMode;
        paybyrdPaymentSettings.PostPaymentOrderStatus = (PostPaymentOrderStatus)model.PostPaymentOrderStatusId;
        paybyrdPaymentSettings.WebhookId = webhookId;
        paybyrdPaymentSettings.HFBackgroundColor = model.HFBackgroundColor;
        paybyrdPaymentSettings.HFPaymentBackgroundColor = model.HFPaymentBackgroundColor;
        paybyrdPaymentSettings.HFPrimaryColor = model.HFPrimaryColor;
        paybyrdPaymentSettings.HFTextColor = model.HFTextColor;

        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.LiveApiKey, model.LiveApiKey_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.TestApiKey, model.TestApiKey_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.PostPaymentOrderStatus, model.PostPaymentOrderStatusId_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.EnableTestMode, model.EnableTestMode_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.WebhookId, model.WebhookId_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.HFBackgroundColor, model.HFBackgroundColor_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.HFPaymentBackgroundColor, model.HFPaymentBackgroundColor_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.HFPrimaryColor, model.HFPrimaryColor_OverrideForStore, storeScope, false);
        await _settingService.SaveSettingOverridablePerStoreAsync(paybyrdPaymentSettings, x => x.HFTextColor, model.HFTextColor_OverrideForStore, storeScope, false);

        await _settingService.ClearCacheAsync();

        _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

        return await Configure();
    }

    public async Task<IActionResult> HandleOrderPostProcessing(int orderId)
    {
        var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
        var settings = await _settingService.LoadSettingAsync<PaybyrdPaymentSettings>(storeScope);

        var order = await _orderService.GetOrderByIdAsync(orderId);
        if (order == null)
        {
            var orderNotFoundMessage = await _localizationService.GetResourceAsync("Plugins.Payments.Paybyrd.OrderNotFound");
            _notificationService.ErrorNotification(orderNotFoundMessage);
            return Redirect(_webHelper.GetStoreLocation());
        }

        var customer = await _workContext.GetCurrentCustomerAsync();
        var currency = order.CustomerCurrencyCode;
        var culture = (await _languageService.GetLanguageByIdAsync(order.CustomerLanguageId))?.LanguageCulture;
        var testModeEnabled = settings.EnableTestMode;
        var apiKey = testModeEnabled ? settings.TestApiKey : settings.LiveApiKey;
        var postPaymentRedirectUrl = $"{_webHelper.GetStoreLocation()}Admin/PaymentPaybyrd/ValidatePayment";

        var requestBody = new
        {
            amount = order.OrderTotal,

Views/Configure.cshtml
@model ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}
@using Nop.Plugin.Payments.Paybyrd.Models

@await Component.InvokeAsync(typeof(StoreScopeConfigurationViewComponent))
<form asp-controller="PaymentPaybyrd" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <p>@T("Plugins.Payments.Paybyrd.Instructions")</p>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="LiveApiKey_OverrideForStore" asp-input="LiveApiKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="LiveApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="LiveApiKey" asp-required="true" html-attributes="@(new { value = Model.LiveApiKey })" />
                        <span asp-validation-for="LiveApiKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TestApiKey" asp-input="TestApiKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TestApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="TestApiKey" html-attributes="@(new { value = Model.TestApiKey })" />
                        <span asp-validation-for="TestApiKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableTestMode_OverrideForStore" asp-input="EnableTestMode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableTestMode" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="EnableTestMode" />
                        <span asp-validation-for="EnableTestMode"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="WebhookId" asp-input="WebhookId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="WebhookId" />
                    </div>
                    <div class="col-md-9">
                        <input asp-for="WebhookId" class="form-control" disabled="disabled" />
                        <span asp-validation-for="WebhookId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PostPaymentOrderStatusId_OverrideForStore" asp-input="PostPaymentOrderStatusId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PostPaymentOrderStatusValues" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PostPaymentOrderStatusId" asp-items="Model.PostPaymentOrderStatusValues" />
                        <span asp-validation-for="PostPaymentOrderStatusId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HFBackgroundColor" asp-input="HFBackgroundColor" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HFBackgroundColor" />
                    </div>
                    <div class="col-md-9">
                        <input type="color" asp-for="HFBackgroundColor" class="form-control" />
                        <span asp-validation-for="HFBackgroundColor"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HFPaymentBackgroundColor" asp-input="HFPaymentBackgroundColor" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HFPaymentBackgroundColor" />
                    </div>
                    <div class="col-md-9">
                        <input type="color" asp-for="HFPaymentBackgroundColor" class="form-control" />
                        <span asp-validation-for="HFPaymentBackgroundColor"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HFPrimaryColor" asp-input="HFPrimaryColor" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HFPrimaryColor" />
                    </div>
                    <div class="col-md-9">
                        <input type="color" asp-for="HFPrimaryColor" class="form-control" />
                        <span asp-validation-for="HFPrimaryColor"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HFTextColor" asp-input="HFTextColor" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HFTextColor" />
                    </div>
                    <div class="col-md-9">
                        <input type="color" asp-for="HFTextColor" class="form-control" />
                        <span asp-validation-for="HFTextColor"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/PaymentInfo.cshtml
@{
    Layout = "";
}
@model Nop.Plugin.Payments.Paybyrd.Models.PaymentInfoModel
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p>
                @Html.Raw(Model.DescriptionText)
            </p>
        </td>
    </tr>
</table>